version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: basicSetupDB
    ports:
      - "5432:5432"
    volumes:
      - basicSetupDB_data:/var/lib/postgresql/data

volumes:
  basicSetupDB_data: